export const Images = {
    logoWithName: require('../../assets/images/logo_name.png'),
    appName: require('../../assets/images/appName.png'),
    appNameWhite: require('../../assets/images/appName_white.png'),
    logo: require('../../assets/images/logo.png'),
    back: require('../../assets/images/back.png'),
    welcomeImage1: require('../../assets/images/welcomeImage1.png'),
    welcomeImage2: require('../../assets/images/welcomeImage2.png'),
    welcomeImage3: require('../../assets/images/welcomeImage3.png'),
    checked: require('../../assets/images/checkbox_checked.png'),
    unchecked: require('../../assets/images/checkbox_unchecked.png'),
    heart: require('../../assets/images/heart.png'),
    search: require('../../assets/images/search.png'),
    person1: require('../../assets/images/person1.png'),
    person2: require('../../assets/images/person2.png'),
    person3: require('../../assets/images/person3.png'),
    noProfile: require('../../assets/images/noProfile.png'),
    edit: require('../../assets/images/edit.png'),
    add: require('../../assets/images/add.png'),
    homeIcon: require('../../assets/images/TabIcons/home.png'),
    chatIcon: require('../../assets/images/TabIcons/chat.png'),
    inboxIcon: require('../../assets/images/TabIcons/inbox.png'),
    profileIcon: require('../../assets/images/TabIcons/profile.png'),
    homeSelectedIcon: require('../../assets/images/TabIcons/home_selected.png'),
    chatSelectedIcon: require('../../assets/images/TabIcons/chat_selected.png'),
    inboxSelectedIcon: require('../../assets/images/TabIcons/inbox_selected.png'),
    profileSelectedIcon: require('../../assets/images/TabIcons/profile_selected.png'),
}