export const AppStrings = {
  byTapping: 'By tapping Create Account or Sign In, you agree to our ',
  terms: 'Terms.',
  learnHow: ' Learn how we process your data in our ',
  privacypolicy: 'Privacy Policy ',
  and: 'and',
  cokkiesPolicy: ' Cookies Policy',
  createAccount: 'CREATE ACCOUNT',
  signIn: 'SIGN IN',
  myNumber: 'My Number is',
  weWillSendCode:
    'We will send a text with a verification code. Message and data rates may apply.',
  continue: 'CONTINUE',
  phoneNumError: '* Please enter valid Phone Number',
  myCode: 'My Code is',
  resend: 'Resend',
  otpError: '* Please enter valid OTP Code',
  whatsYourEmail: "What's your email?",
  dontLose: "Don't lose access to your account,verify your email.",
  enterEmail: 'Enter email',
  emailError: '* Please enter valid Email',
  myFirstName: 'My first name is',
  youWillNotable: 'You will not be able to change this',
  firstName: 'First Name',
  nameError: '* Please enter valid Name',
  birthDate: 'My birthday is',
};