export const AppStrings = {
  appName: 'LoveDrop',
  byTapping: 'By tapping Create Account or Sign In, you agree to our ',
  terms: 'Terms.',
  learnHow: ' Learn how we process your data in our ',
  privacypolicy: 'Privacy Policy ',
  and: 'and',
  cokkiesPolicy: ' Cookies Policy',
  createAccount: 'CREATE ACCOUNT',
  signIn: 'SIGN IN',
  myNumber: 'My Number is',
  weWillSendCode:
    'We will send a text with a verification code. Message and data rates may apply.',
  continue: 'CONTINUE',
  phoneNumError: '* Please enter valid Phone Number',
  phoneRequied: '* Phone Number is required',
  myCode: 'My Code is',
  resend: 'Resend',
  otpError: '* Please enter valid OTP Code',
  whatsYourEmail: "What's your email?",
  dontLoseAccess: "Don't lose access to your account,verify your email.",
  enterEmail: 'Enter email',
  emailError: '* Please enter valid Email',
  emailRequied: '* Email is required',
  myFirstName: 'My first name is',
  youWillNotable: 'You will not be able to change this',
  firstName: 'First Name',
  nameError: '* Please enter valid First Name',
  nameRequied: '* First Name is required',
  nameMin: '* First Name have minimun 3 character',
  birthDate: 'My birthday is',
  dateError: '* Please enter valid Date',
  dateRequied: '* Date is required',
  iam: 'I am a',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  getStared: 'GET STARTED',
  reveal: 'REVEAL',
  welcomeTo: 'Welcome to ',
  connectContact: 'Connect your contacts',
  dontLose: 'Don’t lose.',
  inbox: 'Inbox',
  profile: 'Profile',
  search: 'Search',
  byContact: 'by contact',
  orAddByPhoneNumber: 'or add by phone number ',
  sendDrop: 'SEND DROP',
  sendNote: 'Send Note',
  notes: 'Notes',
  coins: 'Coins',
  termsPrivacy: 'Terms/Privacy',
  logout: 'Log Out',
  anonymousGirlLikedyou: 'An Anonymous Girl Liked You',
  anonymousBoySentNote: 'An Anonymous Boy Sent a Note',
  youSentNote: 'You sent Andrew a Note',
  editProfile: 'Edit Profile',
  updateProfile: 'Update Profile',
  noChatsFound: 'No chats found',


};