// export const Colors = {
//   PRIMARY_COLOR: '#FF2A97',
//   SECONDARY_COLOR: '#D846E4',
//   PRIMARY_BG: '#FFFFFF',
//   PRIMART_TEXT: '#000000',
//   ERROR_TEXT: '#FF0000',
//   PRIMARY_BUTTON_TEXT: '#FFFFFF',
//   LIGHT_TEXT: '#949494',
// };


export interface colorTypes {
  PRIMARY_COLOR: string,
  SECONDARY_COLOR: string,
  PRIMARY_BG: string,
  PRIMART_TEXT: string,
  ERROR_TEXT: string,
  PRIMARY_BUTTON_TEXT: string,
  LIGHT_TEXT: string,
  HOME_INPUT_BG: string,
  SEARCH_INPUT_BG: string,
  PURPLE: string,
  PROFILE_CARD_BG: string,
  PROFILE_CARD_SHADOW: string,
  INBOX_BG: string,
  CHATBOX_BG: string,
  CONTACT_NUMBER: string
}

export const lightThemeColors: colorTypes = {
  PRIMARY_COLOR: '#FF2A97',
  SECONDARY_COLOR: '#D846E4',

  PRIMARY_BG: '#FFFFFF',
  PRIMART_TEXT: '#000000',
  ERROR_TEXT: '#FF0000',
  PRIMARY_BUTTON_TEXT: '#FFFFFF',
  LIGHT_TEXT: '#949494',
  HOME_INPUT_BG: '#D9D9D9',
  SEARCH_INPUT_BG: '#EFEFEF',

  PROFILE_CARD_BG: '#FAE7F1',
  PROFILE_CARD_SHADOW: '#EF5DA8',

  INBOX_BG: '#D9D9D9',
  CHATBOX_BG: '#D9D9D9',

  CONTACT_NUMBER: '#8A8A8D',


  PURPLE: '#72257A'
};

export const darkThemeColors: colorTypes = {
  PRIMARY_COLOR: '#FF2A97',
  SECONDARY_COLOR: '#D846E4',

  PRIMARY_BG: '#000000',
  PRIMART_TEXT: '#FFFFFF',
  ERROR_TEXT: '#FF0000',
  PRIMARY_BUTTON_TEXT: '#000000',
  LIGHT_TEXT: '#EFEFEF',
  HOME_INPUT_BG: '#D9D9D9',
  SEARCH_INPUT_BG: '#EFEFEF',

  PROFILE_CARD_BG: '#EF5DA8',
  PROFILE_CARD_SHADOW: '#FAE7F1',

  INBOX_BG: '#D9D9D9',
  CHATBOX_BG: '#D9D9D9',

  CONTACT_NUMBER: '#8A8A8D',

  PURPLE: '#72257A'
};

// export const redTemeColors: colorTypes = {
//   PRIMARY_BG: "#FF0000",
//   PRIMART_TEXT: "#00FF00"

// }


